@startuml
'https://plantuml.com/class-diagram

title Project Management Application


ProjectDao --> Project
TaskDao --> Task
UserDao --> User


class Project {
    - projectId : String
    - projectName : String
    - createdBy : String
    - tasks : List<String>
}

class Task {
    - taskId : String
    - taskName : String
    - taskDescription : String
    - taskAssignedUsers : List<String>
    - taskDueDate : String
    - taskStatus : String
    - timeSpent : Integer
}

class User {
    - userId : String
    - userName : String
    - userRole : String
    - List<String> taskIds;
}


class UserDao {
    - final dynamoDBMapper : DynamoDBMapper
    - user : User
    - getUserTasks() : List<Task>
    - getUserTasksByPriority() : List<Task>
}

class ProjectDao {
    - final dynamoDBMapper : DynamoDBMapper
    - project : Project
    - createProject() : void
    - getProject() : Project
    - updateProject() : void
    - deleteProject() : void
    - getAllProjects() : List<Project>
}

class TaskDao {
    - final dynamoDBMapper : DynamoDBMapper
    - task : Task
    - createTask() : void
    - getTask() : TaskModel
    - updateTask() : void
    - deleteTask() : void
    - getTasksByProject() : List<Task>
    - getTasksByAssignee() : List<Task>
    - getTasksByAssigneeAndDueDate() : List<Task>
    - updateTaskStatus() : void
    - updateTaskTimeSpent() : void
}

class CreateProjectActivity {
    - final projectDao : ProjectDao
    + handleRequest(CreateTaskRequest request) : CreateTaskResult
}


class AddTaskToProjectActivity {
    - final projectDao : ProjectDao
    - final taskDao : TaskDao
    + handleRequest(AddTaskToProjectRequest request) : AddTaskToProjectResult
}

class GetAllProjectsActivity {
    - final userDao : UserDao
    - handleRequest(GetAllProjectsRequest request) : GetAllProjectsResult
}

class CreateTaskActivity {
    - final taskDao : TaskDao
    + handleRequest(CreateTaskRequest request) : CreateTaskResult
}

class UpdateTaskActivity {
    - final taskDao : TaskDao
    + handleRequest(UpdateTaskRequest request) : UpdateTaskResult
}

class DeleteTaskActivity {
    - final taskDao : TaskDao
    + handleRequest(DeleteTaskRequest request) : DeleteTaskResult
}

class UpdateTasksProgressActivity {
    - final taskDao : TaskDao
    - handleRequest(UpdateTasksProgressRequest request) : UpdateTasksProgressResult
}

class UpdateTaskTimerActivity {
    - final taskDao : TaskDao
    - handleRequest(UpdateTaskTimerRequest request) : UpdateTaskTimerResult
}

class GetAllAssignedTasksActivity {
    - final userDao : UserDao
    - final taskDao : TaskDao
    - handleRequest(GetAllAssignedTasksRequest request) : GetAllAssignedTasksResult
}

class GetAssignedTasksByDueDateActivity {
    - final userDao : UserDao
    - final taskDao : TaskDao
    - handleRequest(GetAssignedTasksByDueDateRequest request) : GetAssignedTasksByDueDateResult
}

@enduml