@startuml
'https://plantuml.com/class-diagram

title Project Management Application

Manager -- ManagerDao
TeamMember -- TeamMemberDao
Task -- TaskDao
TaskAssignees --  TaskAssigneesDao
TaskTime --  TaskTimeDao
TaskFile --  TaskFileDao


class Manager {
    - managerId : String
    - managerName : String
    - managerEmail : String
    - managerPassword : String
    + getManagerId() : String
    + setManagerId() : void
    + getManagerName() : String
    + setManagerName() : void
    + getManagerPassword() : String
    + setManagerPassword() : String
}

class TeamMember {
    - memberId : String
    - memberName : String
    - memberPassword : String
    + getMemberId() : String
    + setMemberId() : void
    + getMemberName() : String
    + setMemberName() : void
    + getMemberPassword() : String
    + setMemberPassword() : void
}


class Task {
    - taskId : String (Partition Key)
    - dueDate : String (Sort Key)
    - taskTitle : String
    - taskDescription : String
    - assignedTo : List<String>
    - assignedBy : String
    - taskStatus : String
    - taskFiles : List<String>
    + getTaskId() : String
    + setTaskId() : void
    + getDueDate() : String
    + setDueDate() : void
    + getTitle() : String
    + setTitle() : void
    + getDescription() : String
    + setDescription() : void
    + getAssignedTo() : List<String>
    + setAssignedTo() : void
    + getAssignedBy() : String
    + setAssignedBy() : void
    + getTaskStatus() : String
    + setTaskStatus() : void
    + getTaskFiles() : List<String>
    + setTaskFiles() : void
}

class TaskAssignees {
    - taskId : String (Partition Key)
    - memberId : String (Sort Key)
    + getTaskId() : String
    + setTaskId() : void
    + getUserId() : String
    + setUserId() : void
}

class TaskTime {
    - taskId : String (Partition Key)
    - memberId : String (Sort Key)
    - taskTimer : Number
    + getTaskId() : String
    + setTaskId() : void
    + getUserId() : String
    + setUserId() : void
    + getTaskTimer() : Number
    + setTaskTimer() : void
}

class TaskFile {
    - fileId : String (Partition Key)
    - fileName : String
    - fileUrl : String
    - taskId : String
    + getFileId() : String
    + setFileId() : void
    + getFileName() : String
    + setFileName() : void
    + getFileUrl() : String
    + setFileUrl() : void
    + getTaskId() : String
    + setTaskId() : void
}



class ManagerDao {
    - final dynamoDBMapper : DynamoDBMapper
    - manager : Manager
    - tasksDao : TasksDao
    - teamMembersDAO : TeamMembersDAO
    + createTask() : void
    + getTask() : List<Tasks>
    + updateTask() : void
    + deleteTask() : void
    + createTeamMember() : void
    + getTeamMember() : List<TeamMember>
    + updateTeamMember() : void
    + deleteTeamMember() : void
}

class TeamMemberDao {
    - final dynamoDBMapper : DynamoDBMapper
    - teamMember : TeamMember
    + createTeamMember() : void
    + getTeamMember() : List<TeamMember>
    + editTeamMember() : void
    + deleteTeamMember() : void
}

class TaskDao {
    - final dynamoDBMapper : DynamoDBMapper
    - task : Task
    + getTask() : Task
    + createTask() : void
    + editTask() : void
    + deleteTask() : void
}

class TaskAssigneesDao {
    - final dynamoDBMapper : DynamoDBMapper
    - assignedTasks : TaskAssignees
    + assignTask() : void
    + getAssignedTasks() : List<Tasks>
    + deleteAssignedTask() : void
}

class TaskTimeDao {
    - final dynamoDBMapper : DynamoDBMapper
    - taskTimer : TaskTime
    + startTimer() : void
    + endTimer() : void
    + getTime() : long
}

class TaskFileDao {
    - final dynamoDBMapper : DynamoDBMapper
    - taskFiles : TaskFile
    + getFile() : String
    + uploadFile() : void
    + deleteFile() : void
}



class CreateTaskActivity {
    - final managerDao : ManagerDao
    + handleRequest(CreateTaskRequest request) : CreateTaskResult
}

class GetTaskActivity {
    - final managerDao : ManagerDao
    + handleRequest(GetTaskRequest request) : GetTaskResult
}

class UpdateTaskActivity {
    - final managerDao : ManagerDao
    + handleRequest(UpdateTaskRequest request) : UpdateTaskResult
}

class DeleteTaskActivity {
    - final managerDao : ManagerDao
    + handleRequest(DeleteTaskRequest request) : DeleteTaskResult
}

class CreateTeamMemberActivity {
    - final managerDao : ManagerDao
    + handleRequest(CreateTeamMemberRequest request) :CreateTeamMemberResult
}

class GetTeamMemberActivity {
    - final managerDao : ManagerDao
    - handleRequest(GetTeamMemberRequest request) : GetTeamMemberResult
}

class UpdateTeamMemberActivity {
    - final managerDao : ManagerDao
    - handleRequest(UpdateTeamMemberRequest request) : UpdateTeamMemberResult
}

class DeleteTeamMemberActivity {
    - final managerDao : ManagerDao
    - handleRequest(DeleteTeamMemberRequest request) : DeleteTeamMemberResult
}

class GetAssignedTasksActivity {
    - final managerDao : ManagerDao
    - handleRequest(GetAssignedTasksRequest request) : GetAssignedTasksResult
}

class StartTaskTimerActivity {
    - final managerDao : ManagerDao
    - handleRequest(StartTaskTimerRequest request) : StartTaskTimerResult
}

class StopTaskActivity {
    - final managerDao : ManagerDao
    - handleRequest(StopTaskRequest request) : StopTaskResult
}

class StartWorkoutActivity {
    - final managerDao : ManagerDao
    + handleRequest(StartWorkoutRequest request) : StartWorkoutResult
}

class StartWorkoutActivity {
    - final managerDao : ManagerDao
    + handleRequest(StartWorkoutRequest request) : StartWorkoutResult
}

class UploadFileActivity {
    - final managerDao : ManagerDao
    + handleRequest(UploadFileRequest request) : UploadFileResult
}

class DeleteTaskActivity {
    - final managerDao : ManagerDao
    + handleRequest(DeleteTaskRequest request) : DeleteTaskResult
}

class GetTaskFilesActivity {
    - final managerDao : ManagerDao
    + handleRequest(GetTaskFilesRequest request) :GetTaskFilesResult
}


class GetTaskTimersActivity {
    - final managerDao : ManagerDao
    + handleRequest(GetTaskTimersRequest request) : GetTaskTimersResult
}


@enduml